# Generated by Django 2.1.5 on 2019-04-06 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Product', verbose_name='Продукт'),
        ),
    ]
